# Generated by Django 5.2.7 on 2025-10-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppleDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AppleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=50)),
                ('version_number', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='appleversion.appledevice')),
            ],
        ),
    ]
